// Package epicrm_apiparts provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package epicrm_apiparts

// ArrayOfPermissions defines model for ArrayOfPermissions.
type ArrayOfPermissions []string

// BusinessId defines model for businessId.
type BusinessId string

// BusinessIdQueryMustParam defines model for businessIdQueryMustParam.
type BusinessIdQueryMustParam string

// BusinessIdQueryOptParam defines model for businessIdQueryOptParam.
type BusinessIdQueryOptParam string

// TenantId defines model for tenantId.
type TenantId string

// TenantIdQueryMustParam defines model for tenantIdQueryMustParam.
type TenantIdQueryMustParam string

// TenantIdQueryOptParam defines model for tenantIdQueryOptParam.
type TenantIdQueryOptParam string
