// Code generated by "stringer -type=Severity"; DO NOT EDIT.

package epicrm_apiparts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Debug-0]
	_ = x[Info-1]
	_ = x[Error-2]
	_ = x[Fatal-3]
}

const _Severity_name = "DebugInfoErrorFatal"

var _Severity_index = [...]uint8{0, 5, 9, 14, 19}

func (i Severity) String() string {
	if i < 0 || i >= Severity(len(_Severity_index)-1) {
		return "Severity(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Severity_name[_Severity_index[i]:_Severity_index[i+1]]
}
